server:
  port: 7002
  session-timeout: 1
  error:
    whitelabel.enabled: false
    path: /error
  tomcat:
    uri-encoding: UTF-8   

ueditor:
 savePath: "/home/ue/"
 readpath: ""     
image:
 imageSavePath: "/home/images/"
  
    
    
spring:
  data:
    solr:
      host: http://114.215.106.58:8085/solr/allData
#       host: http://127.0.0.1:9080/solr/allData
#      host: http://127.0.0.1:8080/solr/allData  http://114.215.106.58:8085/solr/
 