server:
  port: 8083
  session-timeout: 1
  error:
    whitelabel.enabled: false
    path: /error
  tomcat:
    uri-encoding: UTF-8   

ueditor:
 savePath: "D:/home/ue/"
 readpath: ""     
image:
 imageSavePath: "D:/home/images/"
    