server:
  port: 8083
  session-timeout: 1
  error:
    whitelabel.enabled: false
    path: /error
  tomcat:
    uri-encoding: UTF-8   

ueditor:
 savePath: "/home/ue/"
 readpath: ""     
image:
 imageSavePath: "/home/images/"
    