server:
  port: 8080
  error:
    whitelabel.enabled: false
    path: /error
  tomcat:
    uri-encoding: UTF-8   
    
logging:
  level:
    org.springframework.web: DEBUG

ueditor:
 savePath: "D:/111/"
 readpath: ""     
    